// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/1/2025, 11:12:31 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/solongo/assignment/recipe-apptest/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/solongo/assignment/recipe-apptest/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/solongo/assignment/recipe-apptest/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/solongo/assignment/recipe-apptest/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/solongo/assignment/recipe-apptest/app/plugins/**/*.{js,ts,mjs}","/Users/solongo/assignment/recipe-apptest/app/composables/**/*.{js,ts,mjs}","/Users/solongo/assignment/recipe-apptest/app/utils/**/*.{js,ts,mjs}","/Users/solongo/assignment/recipe-apptest/app/pages/index.vue","/Users/solongo/assignment/recipe-apptest/app/pages/login.vue","/Users/solongo/assignment/recipe-apptest/app/pages/recipes/[id].vue","/Users/solongo/assignment/recipe-apptest/app/pages/recipes/saved.vue","/Users/solongo/assignment/recipe-apptest/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/solongo/assignment/recipe-apptest/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/solongo/assignment/recipe-apptest/app/app.config.{js,ts,mjs}","/Users/solongo/assignment/recipe-apptest/app/app/spa-loading-template.html"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;